spring.application.name=adoptions
#
spring.sql.init.mode=always
#
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres

#
spring.ai.vectorstore.pgvector.initialize-schema=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.sse.connections.server1.url=http://localhost:8081

#
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.io.modelcontextprotocol.client=WARN
logging.level.io.modelcontextprotocol.spec=WARN

